---
- name: check /var/www existance and ownership
  file:
    path: /var/www
    state: directory
    mode: 0750
    owner: nginx
    group: nginx

- name: extract wordpress
  unarchive:
    remote_src: yes
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/
