- name: Install pre-requisite packages
  hosts: 185.114.38.84
  tasks:
    - name: install packages
      xbps:
        name: '{{ item }}'
        update_cache: yes
        force: true
        state: latest
      with_items:
        - php
        - nginx
        - mariadb
        - mariadb-client
        - php-fpm
        - php-mysql
